const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('api', {
  watchPetPointer: (enabled) => ipcRenderer.send('pet-pointer-watch', enabled),
  onPetPointer: (cb) => ipcRenderer.on('pet-pointer', (_e, point) => cb(point)),
  setReminder: (provider, enabled) => ipcRenderer.send('set-reminder', provider, enabled),
  onReminders: (cb) => ipcRenderer.on('reminders', (_e, state) => cb(state)),
  onReminderDue: (cb) => ipcRenderer.on('reminder-due', (_e, event) => cb(event)),
  onUsage: (cb) => ipcRenderer.on('usage', (_e, data) => cb(data)),
  onError: (cb) => ipcRenderer.on('usage-error', (_e, msg) => cb(msg)),
  onConfig: (cb) => ipcRenderer.on('config', (_e, cfg) => cb(cfg)),
  saveConfig: (patch) => ipcRenderer.send('save-config', patch),
  resize: (w, h) => ipcRenderer.send('resize', w, h),
  openUsage: (provider) => ipcRenderer.send('open-usage', provider),
  codexDetect: () => ipcRenderer.send('codex-detect'),
  onCodexDetected: (cb) => ipcRenderer.on('codex-detected', (_e, r) => cb(r)),
  codexEnable: (on) => ipcRenderer.send('codex-enable', on),
  onCodex: (cb) => ipcRenderer.on('codex', (_e, c) => cb(c)),
  cursorDetect: () => ipcRenderer.send('cursor-detect'),
  onCursorDetected: (cb) => ipcRenderer.on('cursor-detected', (_e, r) => cb(r)),
  cursorEnable: (on) => ipcRenderer.send('cursor-enable', on),
  onCursor: (cb) => ipcRenderer.on('cursor', (_e, c) => cb(c)),
  onRealUsage: (cb) => ipcRenderer.on('real-usage', (_e, u) => cb(u)),
  onAuthState: (cb) => ipcRenderer.on('auth-state', (_e, s) => cb(s)),
  onProfile: (cb) => ipcRenderer.on('profile', (_e, p) => cb(p)),
  onAuthPending: (cb) => ipcRenderer.on('auth-pending', () => cb()),
  onAuthResult: (cb) => ipcRenderer.on('auth-result', (_e, r) => cb(r)),
  authStart: () => ipcRenderer.send('auth-start'),
  authCode: (code) => ipcRenderer.send('auth-code', code),
  authLogout: () => ipcRenderer.send('auth-logout'),
  onAccounts: (cb) => ipcRenderer.on('accounts', (_e, a) => cb(a)),
  accountSwitch: (id) => ipcRenderer.send('accounts-switch', id),
  accountAdd: () => ipcRenderer.send('accounts-add'),
  accountCancelAdd: () => ipcRenderer.send('accounts-cancel-add'),
  accountRemove: (id) => ipcRenderer.send('accounts-remove', id),
  onDebugState: (cb) => ipcRenderer.on('debug-state', (_e, s) => cb(s)),
  onVersion: (cb) => ipcRenderer.on('version', (_e, v) => cb(v)),
  onUpdateStatus: (cb) => ipcRenderer.on('update-status', (_e, s) => cb(s)),
  checkUpdates: () => ipcRenderer.send('check-updates'),
  doUpdate: () => ipcRenderer.send('do-update'),
  quit: () => ipcRenderer.send('quit'),
})
